# Generated by Django 3.2.2 on 2021-05-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=128)),
                ('desc', models.CharField(default=None, max_length=128)),
                ('stime', models.CharField(default=None, max_length=128)),
                ('etime', models.CharField(default=None, max_length=128)),
                ('isopen', models.CharField(default=None, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('classn', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=8)),
                ('phonenum', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Fquestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('need', models.CharField(max_length=8)),
                ('exampleAnswer', models.TextField(max_length=1024)),
                ('score', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.page')),
            ],
        ),
        migrations.CreateModel(
            name='Fanswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=1024)),
                ('cqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.fquestion')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cquestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('need', models.CharField(max_length=8)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.page')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=8)),
                ('text', models.CharField(default=None, max_length=128)),
                ('score', models.IntegerField(default=1)),
                ('cqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.cquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Canswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=8)),
                ('cqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.cquestion')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.user')),
            ],
        ),
        migrations.CreateModel(
            name='U_P',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4)),
                ('sessionid', models.UUIDField(default=None)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.page')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.user')),
            ],
            options={
                'unique_together': {('pid', 'uid')},
            },
        ),
    ]
