# Generated by Django 3.2.2 on 2021-05-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.TextField(blank=True, max_length=1024, null=True)),
                ('emailTemplate', models.CharField(blank=True, max_length=128, null=True)),
                ('stime', models.DateTimeField(blank=True, null=True, verbose_name='startTime')),
                ('etime', models.DateTimeField(blank=True, null=True, verbose_name='startTime')),
                ('isopen', models.BooleanField(default=False)),
                ('isrunning', models.BooleanField(default=False)),
                ('muid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.BigIntegerField()),
                ('name', models.CharField(default=None, max_length=32)),
                ('school', models.CharField(default=None, max_length=32)),
                ('major', models.CharField(default=None, max_length=32)),
                ('classn', models.CharField(default=None, max_length=32)),
                ('sex', models.CharField(default=None, max_length=8)),
                ('phone', models.CharField(default=None, max_length=32)),
                ('email', models.CharField(default=None, max_length=64)),
                ('muid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('sid', 'muid')},
            },
        ),
        migrations.CreateModel(
            name='Fquestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=None)),
                ('title', models.CharField(default=None, max_length=128)),
                ('desc', models.CharField(blank=True, default=None, max_length=128)),
                ('need', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page')),
            ],
        ),
        migrations.CreateModel(
            name='Fanswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(default=None, max_length=1024)),
                ('fqid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.fquestion')),
                ('uid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Cquestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(default=None)),
                ('title', models.CharField(default=None, max_length=128)),
                ('desc', models.CharField(blank=True, default=None, max_length=128)),
                ('need', models.BooleanField(default=False)),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(default=None, max_length=8)),
                ('text', models.CharField(default=None, max_length=128)),
                ('score', models.IntegerField(default=1)),
                ('cqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.cquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Canswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(default=None, max_length=8)),
                ('cqid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.cquestion')),
                ('uid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='U_P',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sessionid', models.UUIDField(default=None)),
                ('status', models.BooleanField(default=False)),
                ('nums', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page')),
                ('uid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent')),
            ],
            options={
                'unique_together': {('pid', 'uid')},
            },
        ),
    ]
