# Generated by Django 3.2.2 on 2021-05-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(default=None, max_length=8)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('respondent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='FAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(default=None, max_length=1024)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('respondent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent')),
            ],
        ),
        migrations.RenameField(
            model_name='entrance',
            old_name='url',
            new_name='sessionUrl',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
