# Generated by Django 3.2.2 on 2021-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='muid',
            field=models.BigIntegerField(default=None),
        ),
    ]
