# Generated by Django 3.2.2 on 2021-05-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_page_muid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muid',
            field=models.BigIntegerField(default=None),
        ),
    ]
