# Generated by Django 3.2.2 on 2021-05-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_user_muid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'muid')},
        ),
    ]
