# Generated by Django 3.2.2 on 2021-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idd',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('idd', 'muid')},
        ),
    ]
