# Generated by Django 3.2.2 on 2021-05-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210514_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idd',
            new_name='sid',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('sid', 'muid')},
        ),
    ]
