# Generated by Django 3.2.2 on 2021-05-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20210514_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phonenum',
            new_name='phone',
        ),
    ]
