# Generated by Django 3.2.2 on 2021-05-15 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_rename_phonenum_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='canswer',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page'),
        ),
        migrations.AddField(
            model_name='fanswer',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page'),
        ),
        migrations.AlterField(
            model_name='canswer',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.user'),
        ),
        migrations.AlterField(
            model_name='fanswer',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.user'),
        ),
    ]
