# Generated by Django 3.2.2 on 2021-05-15 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_u_p_muid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='stime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='startTime'),
        ),
    ]
