# Generated by Django 3.2.2 on 2021-05-15 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_alter_page_stime'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='startTime')),
            ],
        ),
    ]
