# Generated by Django 3.2.2 on 2021-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='etime',
            field=models.DateTimeField(default=None, verbose_name='startTime'),
        ),
        migrations.AlterField(
            model_name='page',
            name='stime',
            field=models.DateTimeField(default=None, verbose_name='startTime'),
        ),
    ]
