# Generated by Django 3.2.2 on 2021-05-15 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_alter_test_stime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='stime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 11, 1, 11, 177656), verbose_name='startTime'),
        ),
    ]
