# Generated by Django 3.2.2 on 2021-05-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_alter_test_stime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
