# Generated by Django 3.2.2 on 2021-05-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canswer',
            old_name='choice',
            new_name='option',
        ),
    ]
