# Generated by Django 3.2.2 on 2021-05-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_rename_choice_canswer_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanswer',
            old_name='cqid',
            new_name='fqid',
        ),
    ]
