# Generated by Django 3.2.2 on 2021-05-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_rename_cqid_fanswer_fqid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('muid', 'title')},
        ),
    ]
