# Generated by Django 3.2.2 on 2021-05-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_alter_page_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_p',
            name='muid',
        ),
    ]
