# Generated by Django 3.2.2 on 2021-05-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_remove_u_p_muid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Respondent',
        ),
    ]
