# Generated by Django 3.2.2 on 2021-05-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0022_rename_user_respondent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
