# Generated by Django 3.2.2 on 2021-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0023_alter_page_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_p',
            name='status',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
