# Generated by Django 3.2.2 on 2021-05-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_u_p_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='cqid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.cquestion'),
        ),
        migrations.AlterField(
            model_name='canswer',
            name='option',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='desc',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='need',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page'),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='fanswer',
            name='answer',
            field=models.TextField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='fanswer',
            name='fqid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.fquestion'),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='desc',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='exampleAnswer',
            field=models.TextField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='need',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page'),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='classn',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='email',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='major',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='phone',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='school',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='sex',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='u_p',
            name='pid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.page'),
        ),
        migrations.AlterField(
            model_name='u_p',
            name='type',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='u_p',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.respondent'),
        ),
    ]
