# Generated by Django 3.2.2 on 2021-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0029_u_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='emailTemplate',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
