# Generated by Django 3.2.2 on 2021-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0030_page_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='isrunning',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
