# Generated by Django 3.2.2 on 2021-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0031_page_isrunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_p',
            name='status',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
