# Generated by Django 3.2.2 on 2021-05-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0032_alter_u_p_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='isopen',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
