# Generated by Django 3.2.2 on 2021-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0033_alter_page_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquestion',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
