# Generated by Django 3.2.2 on 2021-05-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0034_auto_20210520_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fquestion',
            name='exampleAnswer',
        ),
    ]
