# Generated by Django 3.2.2 on 2021-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0035_remove_fquestion_exampleanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquestion',
            name='need',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fquestion',
            name='need',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='isopen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='isrunning',
            field=models.BooleanField(default=False),
        ),
    ]
