# Generated by Django 3.2.2 on 2021-05-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0036_auto_20210520_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u_p',
            name='type',
        ),
    ]
