# Generated by Django 3.2.2 on 2021-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0038_alter_u_p_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='desc',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
