# Generated by Django 3.2.2 on 2021-05-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_emailcode'),
        ('question', '0039_alter_page_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='muid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
