# Generated by Django 3.2.2 on 2021-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0041_alter_page_muid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u_p',
            old_name='sessionid',
            new_name='sessioni',
        ),
    ]
