# Generated by Django 3.2.2 on 2021-05-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0042_rename_sessionid_u_p_sessioni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u_p',
            old_name='sessioni',
            new_name='sessionid',
        ),
    ]
