# Generated by Django 3.2.2 on 2021-05-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0043_rename_sessioni_u_p_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canswer',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='fanswer',
            name='pid',
        ),
    ]
