# Generated by Django 3.2.2 on 2021-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0044_auto_20210522_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_p',
            name='nums',
            field=models.IntegerField(default=0),
        ),
    ]
