# Generated by Django 3.2.2 on 2021-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0046_remove_u_p_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_p',
            name='nums',
            field=models.IntegerField(default=0),
        ),
    ]
