# Generated by Django 3.2.2 on 2021-05-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0047_u_p_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_p',
            name='uid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent'),
        ),
    ]
