# Generated by Django 3.2.2 on 2021-05-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0048_alter_u_p_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canswer',
            name='uid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent'),
        ),
        migrations.AlterField(
            model_name='fanswer',
            name='uid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.respondent'),
        ),
    ]
