# Generated by Django 3.2.2 on 2021-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('token', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=15)),
                ('email', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
