# Generated by Django 3.2.2 on 2021-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210513_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailcode',
            field=models.IntegerField(default=None),
        ),
    ]
