# Generated by Django 3.2.2 on 2021-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_emailcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailcode',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
