# Generated by Django 3.2.2 on 2021-05-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_emailcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPTCHA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default=None, max_length=32)),
            ],
        ),
    ]
